### ISSUE TITLE
Fatal error right before installation

### ISSUE THREAD

**Issue by kekh** [gh2o/digitalocean-debian-to-arch#14]
Hello,

I got these errors after the script downloaded all the packages and just before styarting the install: "error: could not determine cachedir mount point /packages"
"error: failed to commit transaction (not enough free disk space)" just right before the installation.

How may I go forward please?

Thanks

Here is some infos:

uname -a => Linux v1871 2.6.32-openvz-042stab106.4-amd64 #1 SMP Fri Mar 27 15:27:00 MSK 2015 x86_64 GNU/Linux

before errors => :: Synchronizing package databases...
 core                                                                       122.3 KiB   501K/s 00:00 [###########################################################] 100%
 extra                                                                     1726.7 KiB   669K/s 00:03 [###########################################################] 100%
 community                                                                    2.7 MiB   733K/s 00:04 [###########################################################] 100%
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: ncurses will be installed before its bash dependency

Packages (128) acl-2.2.52-2  archlinux-keyring-20150523-1  attr-2.4.47-1  ca-certificates-20150402-1  ca-certificates-cacert-20140824-2 [...] vi-1:070224-1  which-2.21-1  xfsprogs-3.2.2-1

Total Download Size:   114.13 MiB
Total Installed Size:  517.09 MiB

:: Proceed with installation? [Y/n] 
error: could not determine cachedir mount point /packages
error: failed to commit transaction (not enough free disk space)
Errors occurred, no packages were upgraded.
[Tue Jun  2 06:02:23 CEST 2015] Cleaning up ...

**Comment by gh2o** [comment]
I'm unable to reproduce this. What distro are you running this on? This script only officially supports Debian 7.x on amd64.

**Comment by kekh** [comment]
Ouch :-( actually it's Debian Weezy (7)

**Comment by kekh** [comment]
Maybe you want another commands output ? This is a fresh installed VDS, with almost nothing...

**Comment by gh2o** [comment]
That is quite odd. Just wondering, are you using DigitaOcean? 2.6.32-openvz-042stab106.4-amd64 is not a kernel version I'm familiar with.

**Comment by kekh** [comment]
Nope, I thought it was a "generic" solution...
Do you want a root access ? Or maybe you have an idea of something where investigate? :-/

**Comment by gh2o** [comment]
Unfortunately for OpenVZ based VPSes, installing Arch Linux would be sub-optimal because it's not possible to run your own kernel. You could try installing it into a directory ( https://wiki.archlinux.org/index.php/Install_from_existing_Linux ) and see how it goes from there.

**Comment by kekh** [comment]
Man your right, I'm totally stuck with Debian and with this strange VPS provider... What a terrible mistake to not choosing a trully good provider...
In 3 months, I'll go suscribe to DigitalOcean because seems much more serious... Beside, would you have a referal link for them?

Thank you anyway for your help!

**Comment by gh2o** [comment]
You can probably find referral codes worth more out there, but here's $10: https://www.digitalocean.com/?refcode=8bee824ad0f6

**Comment by kekh** [comment]
Thank you very much, again :-)
