### ISSUE TITLE
Stuck for a long time after reboot

### ISSUE THREAD

**Issue by yuvadm** [gh2o/digitalocean-debian-to-arch#15]
This is what the VNC console shows:
![screen shot 2015-06-24 at 13 47 57](https://cloud.githubusercontent.com/assets/315080/8328243/b3922e04-1a77-11e5-8724-66c13bbe336c.png)

**Comment by yuvadm** [comment]
After several minutes the machine becomes available. Don't know if this is a bug or not.

**Comment by gh2o** [comment]
Interesting. Was the percentage meter stuck?

**Comment by yuvadm** [comment]
Nope, just took an awful long time. I didn't check how long but I think somewhere around 30-40% it took off fast and finished.

**Comment by gh2o** [comment]
Hmm that's odd. I just tried it on a brand new droplet, and it was only down for about 20 seconds before I could SSH back into again. What settings did you use for your droplet? (region, size, etc.)

**Comment by yuvadm** [comment]
Debian 8.1 64, Amsterdam 3, 8GB RAM instance.

**Comment by gh2o** [comment]
I just tried it out with those settings and it still comes back up within 25 seconds. I'm starting to think the pause might've been due to a server hiccup, since a couple GBs of data are shuffled during the downtime and the heavy I/O might have triggered it.

**Comment by yuvadm** [comment]
Fair enough, let's close the issue and leave it here for posterity. Thanks :)
