### ISSUE TITLE
Way to append systemd-networkd configuration?

### ISSUE THREAD

**Issue by kylemanna** [gh2o/digitalocean-debian-to-arch#16]
Hi,

Thanks for the script, it just worked and I was impressed to see that you went the extra mile to use systemd-networkd and even create a PKGINFO!

Quick question/feature request:  Is there a good way to append to the `/run/systemd/network/dosync-eth0.network` file?  I need to append `Tunnel=he-ipv6` for a [IPv6 tunnel](https://wiki.archlinux.org/index.php/IPv6_tunnel_broker_setup#systemd-networkd) service I'm using.

I hacked up `digitalocean-synchronize` to do this, [but it doesn't feel right](https://gist.github.com/67399a88701d120b2fc0/revisions).

**Comment by gh2o** [comment]
You're welcome! And good point. I would suggest copying `/run/systemd/network/dosync-eth0.network` to `/etc/systemd/network/custom-eth0.network` and making the necessary modifications there. A major downside of this approach if the droplet is recreated with a different IP address (via clone or restore), you would lose networking until it's reconfigured via console. Would that work in your case?

**Comment by kylemanna** [comment]
Wouldn't that cause two networks to match the eth0 interface?

**Comment by gh2o** [comment]
Yes, but files in /etc take precedence over files in /run, so the generated
file would be ignored.
