### ISSUE TITLE
Add instructions how to upgrade existing Debian 7 installs to Debian 8

### ISSUE THREAD

**Issue by strelec** [gh2o/digitalocean-debian-to-arch#19]
Since version 8 doesn't have to use kexec hacks, it is probably a better idea, but having a day of downtime to migrate manually (backup & restore) is not acceptable in my case.

The administration panel supports changing the kernel, but I am not sure it would work out of the box.

```
Select a kernel and click change.

This will update your configuration. Then power off the server from the command line and boot it from the Control Panel and the new kernel will be active. To revert, simply select 'Original Kernel' and follow the same process.

Your droplet's current kernel: Debian 7.0 x64 vmlinuz-3.2.0-4-amd64 (3.2.65-1+deb7u1)
```

**Comment by gh2o** [comment]
Machines created on the Debian 7 image boot using a predefined DigitalOcean-provided kernel, whereas machines created on the Debian 8 image boot from the MBR like a real PC. Unfortunately there's no way to convert between them, so for now it seems like the backup-restore process might be the only option.

**Comment by strelec** [comment]
That's unfortunate.

Is there any chance of something going wrong in the future with existing Debian 7 installations (future kernel upgrades with pacman)?

**Comment by gh2o** [comment]
Not that I know of. The only issue I foresee is systemd gaining a kernel dependency that is not supported by the DO Debian kernel, but given that Debian 8 (and presumably future versions) use systemd, that is highly unlikely.

**Comment by strelec** [comment]
Thanks. In case you figure something out, I'd very much like to hear it.
