### ISSUE TITLE
Cryptsetup Support possible?

### ISSUE THREAD

**Issue by Mic92** [gh2o/digitalocean-debian-to-arch#20]
I saw, it is possible to use btrfs now.
So I wonder if cryptsetup with this [initrd](https://github.com/suiryc/archlinux-initrd-ssh-cryptsetup) works, too.

**Comment by gh2o** [comment]
This script only sets up a minimal Arch Linux install with network access; adding encryption support is out of the scope of this project. That being said, you do have that option. Here are the general steps:
1. Create a new Debian8 droplet and convert it to Arch Linux with the option `--target_filesystem=btrfs`.
2. On the droplet, use `btrfs filesystem resize` to resize the root partition to about 4 GB.
3. Using `fdisk`, update the entry for the root partition to reflect the change to 4 GB, then create a 4 GB LVM partition near the end of the disk.
4. Use `pvcreate` to format the LVM partition.
5. Use `vgcreate` to create a volume group containing the above partition.
6. Use `lvcreate` to create a small boot partition.
7. Use `lvcreate` to create a logical volume filling the whole volume group.
8. Create a new LUKS partition at `/dev/mapper/<vg_name>-<lv_name>`, and specify the password here.
9. Use `cryptsetup` to enable the new LUKS partition, then format it as btrfs.
10. Mount the partition created at the previous step. Also mount the created boot partition.
11. Copy /boot to the boot partition and everything else to the new root partition.
12. Install your cryptsetup script in the new partition (via chroot), then reinstall Grub from the new (encrypted) partition, ensuring that /boot is mounted within the new partition.
13. Reboot. If everything worked properly, your cryptsetup script should work, and your new root should be the encrypted partition.
14. (Optional) Delete the old root partition.
15. Use `fdisk` to create a new LVM partition filling up the free space left on the disk.
16. Use `pvcreate` to initialize the LVM partition, then `vgextend` to add it to the volume group.
17. Use `lvextend` to resize the root partition to fill the volume group.
18. Use `cryptsetup resize` to resize the encrypted container to fill up the logical volume.
19. Finally, use `btrfs filesystem resize` to fill the encrypted container with the btrfs filesystem.

Hope this helps!

**Comment by Mic92** [comment]
Thanks for this extensive instructions
