### ISSUE TITLE
Lost connection to droplets

### ISSUE THREAD

**Issue by Narga** [gh2o/digitalocean-debian-to-arch#21]
I've tried your scripts, it's work well as I expected but I found the problem, if I upgrade `digitalocean-synchronize` from AUR, my droplet will lost the network and I can't connect to fixing it. All things to do is rebuild the droplet from the beginning.

**Comment by gh2o** [comment]
That is unfortunate and I apologize for the issue. If you're unable to connect to the droplet but know the root password, you can use the Console Access page on the DigitalOcean panel. If you do not know the root password or failed to set one, do the following:
1. Open up a tab on Console Access.
2. In another tab, reboot the droplet.
3. Refresh the Console Access page until the console shows up. You will have 10 seconds before Grub starts booting Linux.
4. Press `e` to edit the first entry.
5. At the end of the line that begins with `linux`, add the following: `rw init=/bin/bash`
6. Press Ctrl-X or F10 to boot.
7. When the prompt appears, run `passwd` to set a root password.
8. Continue booting the system by running `exec /sbin/init`.
9. Log in as usual.

In order for me to debug this, could you please post the output from `journalctl -b` after running the above? Thanks!

**Comment by Narga** [comment]
Thanks for your support, fortunately, it has occured before I move my website to new droplet that switch from debian to arch linux.
After that, I've rebuilt the droplet, mark `digitalocean-synchronize` as NoUpgrade package then it works well.
I will create new droplet then follow your guide and send the debug messages late.

**Comment by gh2o** [comment]
Thank you!

**Comment by Narga** [comment]
I've follow as your guide but the system always told me that password is incorrect. I'm type it correctly.

**Comment by gh2o** [comment]
Where does it tell you this? Have you reset your password with `passwd`?

**Comment by Narga** [comment]
Yes, reset it with `passwd`

**Comment by Narga** [comment]
It's only occurred if I upgrade `digitalocean-synchronize-2.4-1` to `digitalocean-synchronize-2.4-2`

**Comment by gh2o** [comment]
Can you post the output of `journalctl | grep digital` from the initial shell

**Comment by Narga** [comment]
I can't login so I can't running any command

**Comment by gh2o** [comment]
Can you run it from the initial shell (the one where you were able to run `passwd`)

**Comment by gh2o** [comment]
And @kylemanna, do you know what could be causing this?

**Comment by Narga** [comment]
http://i.imgur.com/liA9oVk.png

**Comment by gh2o** [comment]
I mean, can I get the output for it after the install (when the login fails) in the shell right after manually booting from Grub (see https://github.com/gh2o/digitalocean-debian-to-arch/issues/21#issuecomment-131497712 for details).

**Comment by Narga** [comment]
It's too long to find, and I take the screen at the possition when login fail
http://imgur.com/DVKGiAnl.png

**Comment by ijaaz** [comment]
@Narga How did you mark `digitalocean-synchronize` as a NoUpgrade package? I also encountered this issue & cannot find the `digitalocean-synchronize` file to mark as NoUpgrade via pacman.conf

**Comment by Narga** [comment]
You can add in into the `/etc/pacman.conf` file
