### ISSUE TITLE
systemd 225 -> 226  breaks network config on all converted vm's

### ISSUE THREAD

**Issue by nlyan2025** [gh2o/digitalocean-debian-to-arch#22]
The system update from systemd 225 to 226 seems to have renamed network interfaces. After an update, and a reboot, all converted  VMs will be offline.

I don't know if digitalocean-synchronize needs to  be updated to block systemd >=226 and/or a new version that uses the  "ens" interface names needs to  be released, but everything is down

**Comment by gh2o** [comment]
I've fixed this bug by disabling renaming for virtio network devices. Any affected users should simply redownload the script and run it again; this will apply the fix by updating the digitalocean-synchronize package.

**Comment by strelec** [comment]
Here, you have said there is unlikely that something is to break Debian 7 installations. Yet it happened.

https://github.com/gh2o/digitalocean-debian-to-arch/issues/19

**Comment by gh2o** [comment]
This was a systemd change, not a kernel change. Is the same problem present on the debian7 branch?

**Comment by strelec** [comment]
Of course. It broke completely and it took me 2 hours to find the culprit.

**Comment by achilleas-k** [comment]
I've been trying to get out of this situation for a while now.

I can't downgrade systemd; the package cache is (likely) set to clear old packages and 225 has been removed.
I can't download the updated debian-to-arch script (no network).
I checked the patch that fixes this issue to see what needed to be changed, and I created `/usr/lib/systemd/network/90-virtio-no-rename.link` with the following content:

```
[Match]
Driver=virtio_net
[Link]
NamePolicy=kernel
```

Now, on boot, the device names aren't changed (I have `eth0` and `eth1`), but the network is still not connected. I've manually added the droplet's IP using `ip addr add <IP> dev eth0` with no success.

Am I missing something? Can someone help point me to the correct way of configuring the network, or is there something else I need to do?

**Comment by gh2o** [comment]
You need to add the default route (ip route add default via <gateway>). Once you get back online, can you post the relevant journalctl for systemd-networkd? Thanks!

**Comment by achilleas-k** [comment]
Indeed, setting the route did it.
Here's the output of `journalctl -b --unit=systemd-networkd`.

```
─> journalctl -b --unit=systemd-networkd
-- Logs begin at Tue 2015-09-08 13:52:36 EEST, end at Sat 2015-10-03 19:55:17 EEST. --
Oct 03 19:42:39 Dranus systemd[1]: Starting Network Service...
Oct 03 19:42:39 Dranus systemd-networkd[191]: Enumeration completed
Oct 03 19:42:39 Dranus systemd[1]: Started Network Service.
Oct 03 19:43:32 Dranus systemd[1]: Starting Network Service...
Oct 03 19:43:32 Dranus systemd-networkd[478]: Enumeration completed
Oct 03 19:43:32 Dranus systemd[1]: Started Network Service.
```

Nothing interesting there. Greping `journalctl -b` for `network` shows nothing interesting either.
