### ISSUE TITLE
Root password after reboot?

### ISSUE THREAD

**Issue by novemberist** [gh2o/digitalocean-debian-to-arch#23]
After the installation has finished and the system rebooted, what is my root password? I'm trying to connect to the server via ssh and it won't accept the old root password from my Debian droplet (neither the default one by Digitalocean nor the one i had changed it to)

**Comment by novemberist** [comment]
This seems to be a problem with ssh only. I can login with my root password using the VNC Console. But it doesnt recognize any key presses after login.

**Comment by kan-uddf** [comment]
getting the same issue, started with a brand new Debian 8.1 x64 logged in with the supplied password, was prompted to change it, changed it ran the script, system rebooted and old password or new password no longer works, repeated this process 3 times and am thinking its not a typo by my self now.

passwords do not work via ssh or console.

**Comment by gh2o** [comment]
Thank for reporting the issue. The problem is that in newer versions of OpenSSH, PermitRootLogin defaults to "prohibit-password" by default, so root logins using a password is prohibited. The script now sets PermitRootLogin to yes if public keys are not enabled, and outputs a warning in the log.
