### ISSUE TITLE
Default DNS 8.8.8.8

### ISSUE THREAD

**Issue by yuvadm** [gh2o/digitalocean-debian-to-arch#24]
Why is the default DNS set to `8.8.8.8`? And where is this config set? By default I don't see anything in `/etc/netctl` or in `/etc/systemd/network` so I wonder...

The sane default should be to use the gateway as DNS, and not some external g00gle service.

**Comment by gh2o** [comment]
DigitalOcean sets up 8.8.8.8 as the DNS server by default on new droplets, so I hardcoded it into the install script. http://169.254.169.254/metadata/v1/dns/nameservers also shows the same nameservers.

**Comment by yuvadm** [comment]
I suppose if digital ocean doesn't supply any DNS server of their own this issue is moot. Kinda bummed about that tho :/

**Comment by gh2o** [comment]
I've run a local recursive BIND resolver instance on mine and it works pretty well.

**Comment by yuvadm** [comment]
@gh2o using which upstream DNS server?

**Comment by gh2o** [comment]
You do not need an upstream server; the recursive resolver queries the root DNS servers. See https://wiki.archlinux.org/index.php/BIND#3._Setting_this_to_be_your_default_DNS_server

**Comment by yuvadm** [comment]
I don't see this mentioned explicitly, but I assume that's just how BIND works?

**Comment by gh2o** [comment]
Yes, in recursion mode, BIND only queries the authoritative nameservers.

http://serverfault.com/questions/661821/what-s-the-difference-between-recursion-and-forwarding-in-bind

**Comment by yuvadm** [comment]
@gh2o awesome, thanks for the clarification!
