### ISSUE TITLE
DigitalOcean Archlinux is down

### ISSUE THREAD

**Issue by vodik** [gh2o/digitalocean-debian-to-arch#26]
The Archlinux mirror is currently 404'ing, don't know if it'll come back.

**Comment by tmathmeyer** [comment]
I'm having this problem too. I've pointed my mirrors at 
Server = http://mirrors.acm.wpi.edu/archlinux/$repo/os/$arch

**Comment by gh2o** [comment]
Thanks for the notification. I've switched the mirror to Rackspace, an official worldwide mirror.
