### ISSUE TITLE
Floating IP?

### ISSUE THREAD

**Issue by kiddyfurby** [gh2o/digitalocean-debian-to-arch#29]
Do we have support for [floating ip](https://www.digitalocean.com/company/blog/floating-ips-start-architecting-your-applications-for-high-availability/)?

I was following [this guide](https://www.digitalocean.com/community/tutorials/how-to-enable-floating-ips-on-an-older-droplet) to setup floating ip to no avail
it seems that changes to /etc/systemd/network/static.network has no effect on /var/run/systemd/network/ens3.network?

**Comment by maki-chan** [comment]
Should be closed since #35 is merged

**Comment by gh2o** [comment]
Thanks!
