### ISSUE TITLE
cannot type at console?

### ISSUE THREAD

**Issue by nhooyr** [gh2o/digitalocean-debian-to-arch#31]
For some reason I cannot type at the console, no idea what is wrong. I can get output to appear by running the command `echo "dasldsjkjdkajkls" > /dev/console`. I can also read the console from the command line with `cat /dev/vcs`. Just cannot type anything in my browser. 

Tested on multiple browsers (latest safari and chrome), I can login via ssh and use it perfectly. I tried power cycling as well. Digital ocean support said they can't help me because I used this script.

Any ideas?

**Comment by lloeki** [comment]
What kind of KB layout are you using? DO's VNC console is a bit rough (mostly due to JS limitations) and basically requires using a US layout on both ends so that keycodes map correctly.

**Comment by nhooyr** [comment]
Unfortunately, I don't use arch on digital ocean anymore.

Sorry!

I was using a regular US keyboard btw.
