### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by ghost** [gh2o/digitalocean-debian-to-arch#32]
> wget https://raw.githubusercontent.com/gh2o/digitalocean-debian-to-arch/debian8/install.sh && bash install.sh

This isn't an acceptable way to install software unless you have severe mental disabilities.

E: typos

**Comment by gh2o** [comment]
Would you like to suggest a better way to distribute this script?

The fact that the README states "ALL DATA ON THE DROPLET WILL BE UNCONDITIONALLY DESTROYED" makes clear the intention of this script.

**Comment by KrzaQ** [comment]
You could make it a `.deb` package within your repository and provide the lines necessary to add and run it from the console. It's advantage would be making code-signing possible, but you'd have to add your key to the trust list making this security feature moot (unless .

That being said, you might want to read the [D's forum discussion on similar installer used by Rust](http://forum.dlang.org/post/bxdpurhrtokulutndffh@forum.dlang.org) -- at the very least the idea about wrapping everything into a function and calling it at the end of the script to prevent half-finished downloads from executing.

**Comment by gh2o** [comment]
The "&&" in the wget command ensures that the script does not run if it is not fully downloaded.

Honestly, for a package not in the official repo, wouldn't packaging up a single script make the process even less transparent? There would be nothing stopping me from adding malicious code into the post-install script, which would be more effort to inspect than simply opening up this script with a text editor.

**Comment by tmathmeyer** [comment]
The issue with this isn't that it could be corrupted, but rather that you could MITM'd. That being said, this script is generally to be run on a completely fresh install makes this quite a moot point. The best you could do I think is to pipe it to less after downloading and before running, and put the responsibility of security on the users shoulders, is:

wget https://raw.githubusercontent.com/gh2o/digitalocean-debian-to-arch/debian8/install.sh && less install.sh && bash install.sh

**Comment by injust** [comment]
> The "&&" in the wget command ensures that the script does not run if it is not fully downloaded.

It may be advisable to change the command to `wget https://raw.githubusercontent.com/gh2o/digitalocean-debian-to-arch/debian8/install.sh -O install.sh && bash install.sh` so that wget is forced to overwrite any existing install.sh instead of downloading to install.sh.1. This way, you don't end up running a partially-downloaded install.sh if wget successfully downloads install.sh.1 in the second execution.

**Comment by jcaesar** [comment]
How could it be MITM'd? And why would someone who has the ability to break https or gh2o's github account not also have the ability to beak package signing or put some false information on how to verify the script's integrity here?

**Comment by tmathmeyer** [comment]
For starters, being MITM'd is actually a lot easier than you think (for example, DO could be authenticating certs at the hypervisor or data center level, though they probably arent). Basically checking the script over once, sha1ing it, etc. are all just added levels of security.

**Comment by gh2o** [comment]
@Injust That is a great idea. Thanks for the suggestion; will add now.

**Comment by ghost** [comment]
> The fact that the README states "ALL DATA ON THE DROPLET WILL BE UNCONDITIONALLY DESTROYED" makes clear the intention of this script.

Intention is not same as the risk here. This script could be diverted into also infecting the new image with malware or to install already malicious image.

**Comment by gh2o** [comment]
@Tsutsukakushi When was the last time you downloaded a program and read its full source code before running it?
