### ISSUE TITLE
Cannot login to machines built from a debian-to-arch image?

### ISSUE THREAD

**Issue by logankoester** [gh2o/digitalocean-debian-to-arch#33]
I cannot seem to use this to create a reusable archlinux image for myself, and I'm not sure I understand why.

When I run the script and reboot the box, I have a seemingly perfect arch droplet, so then I image it. But when I create a new droplet from the image, it refuses SSH connections (on 22) and I also cannot use the DO console because the root password has changed.

The genesis droplet works fine.

It doesn't seem to be a networking issue (the public IP responds to ping).

Any idea what I'm missing here? Thanks.

**Comment by FirefighterBlu3** [comment]
are you doing anything at all different than creating a DO with an ssh key, logging in, and running the script? i just built multiple droplets a couple days ago and it worked perfectly

**Comment by logankoester** [comment]
Thanks @FirefighterBlu3, here is my exact process:
1. Create a droplet (Debian 8.3 x64, with Private Networking, IPv6, with SSH key)
2. `ssh root@$DROPLET`
3. `passwd`
4. `wget https://raw.githubusercontent.com/gh2o/digitalocean-debian-to-arch/debian8/install.sh && bash install.sh`
5. Shutdown the droplet & create an image.
6. Create a droplet from the image
7. Can't connect to it via SSH, can't use chosen root password via DO console). Original droplet still works fine.

Anything obviously PEBKAC? Can you reproduce the issue?

**Comment by tomkwok** [comment]
I had the same problem and rebooting (power cycling in the DO panel) the freshly created droplet after your step 6 seemed to work for me. I'd also like to know what caused the issue.

**Comment by FirefighterBlu3** [comment]
@logankoester step #3 is not going to be of any value to you, the deb2arch wipes out the deb filesystem and creates a brand new arch installation. afaik, the ssh key(s) are the only thing kept from the deb FS. if you need to use the password login instead of ssh key, you'll need to insert that at 4.5. also, i've never used an image clone.

here's my process.
1. create deb 8.3 droplet with those same options
2. ssh root@
3. wget and run
4. reboot

at this point, my droplet is a fully functioning arch system, i'll ssh root@, set passwd, install additional software, add web pages, etc.

**Comment by logankoester** [comment]
@FirefighterBlu3 I see, I suppose I misunderstood when [update_shadow_if_changed()](https://github.com/gh2o/digitalocean-debian-to-arch/blob/debian8/install.sh#L873) is called.

**Comment by FirefighterBlu3** [comment]
understandable -- it's just not worked for me so i ignored it

**Comment by gh2o** [comment]
Root password and authorized SSH keys are reset upon image creation by the `digitalocean-synchronize` script upon first bootup.

- If SSH keys are configured on the droplet creation page, these are the keys that will be used, root password login is disabled.
- If SSH keys are not configured, the root password is reset to the one DO emails you.
