### ISSUE TITLE
Feature option: create swap space

### ISSUE THREAD

**Issue by HLFH** [gh2o/digitalocean-debian-to-arch#34]
Hi,

We should be able to have the feature option `--swap`. For example `--swap 2GB`.

Thanks,
HLFH

**Comment by nitrix** [comment]
IIRC; DO's hyperviser doesn't let you do swapping.

**Comment by lloeki** [comment]
The, *ahem*, recommended way (really, *not* recommended, you should get by without swap) is to create a swap file that'll get used only in the most dire memory situations:

```
touch /var/swap
chmod 600 /var/swap
fallocate -l $(free -b | grep Mem | awk '{ print $2 }') /var/swap
mkswap /var/swap
sysctl $(echo 'vm.swappiness=10' | tee /etc/sysctl.d/50-swap.conf)
echo '/var/swap none swap sw 0 0' >> /etc/fstab
swapon -a
free | grep 'Swap'
```

**Comment by HLFH** [comment]
Ok. The `swapfile` method is the one I used. And there is a `won't fix` about the swap space support with DO.
