### ISSUE TITLE
Flag: confirm "wipe this droplet"

### ISSUE THREAD

**Issue by unixfox** [gh2o/digitalocean-debian-to-arch#38]
I want to integrate this script inside an automated build system but I've to handle the confirmation after running the script:
````
[Mon Nov 28 19:14:59 UTC 2016] Type "wipe this droplet" to continue or anything else to cancel.
````
Is it possible to add a flag to the script to skip this confirmation?

**Comment by gh2o** [comment]
The script accepts the `--i_understand_that_this_droplet_will_be_completely_wiped` flag to do so.

**Comment by unixfox** [comment]
Thank you I didn't see this flag inside the README section `Advanced Configuration`.

**Comment by gh2o** [comment]
You're welcome. I intentionally left it undocumented because I wanted the warning to be completely clear via the script.
