### ISSUE TITLE
Number of inodes

### ISSUE THREAD

**Issue by dima74** [gh2o/digitalocean-debian-to-arch#43]
Thank for script! Please add an option to configure number of inodes, more precisily bytes-per-inode ratio. It is `-i` parameter of `mkfs` command.

**Comment by gh2o** [comment]
Thanks for the suggestion! To make it more generic, I added the `--mkfs_options`, so in your case you could use it as e.g. `--mkfs_options="-i 128"`

**Comment by dima74** [comment]
Thank you!
