### ISSUE TITLE
Why GPT?

### ISSUE THREAD

**Issue by ghost** [gh2o/digitalocean-debian-to-arch#44]
Why is GPT important? The main advantage of GPT is working with large disks (2+ TB), and digital ocean's largest primary SSD size is 640GB. Arch doesn't prefer GPT over MBR or anything either, so it seems like specifying partition table preference, and especially defaulting it to GPT introduces a lot of complexity to the script to no real benefit.

Not really a complaint or anything, I just don't understand why GPT is considered at all. I am using this script to good effect either way. Thank you for releasing/maintaining it publicly :+1: :+1:

**Comment by gh2o** [comment]
The way I see it, GPT is standard for all other modern OSes today (and many Linux installations too). Choosing GPT future-proofs the installation in the possible case that DO decides to start offering 2TB+ disks, and I wouldn't say it adds too much additional complexity :smile:
