### ISSUE TITLE
Debian 9.0 support

### ISSUE THREAD

**Issue by lloeki** [gh2o/digitalocean-debian-to-arch#46]
Debian 9.0 is now available on DO. Debian 8.x is still available but it would be great to keep things up to date :)

**Comment by lloeki** [comment]
FYI, plowing through:

- replaced `8.?` by `9.?` in the debian version check
- `apt-get update` for the script to be able to install `haveged` (or anything else, really)
- `apt-get install xz-utils` for missing `xz` command
- `apt-get install psmisc` for missing `fuser` command
- `apt-get install busybox-static` for missing `/bin/busybox` on `cp`

I had lots of those, but did have a `cp` error for `/bin/busybox`, so it did went throught `stage2_arrange` into `stage3_prepare`:

```
[Wed Jun 21 09:59:31 UTC 2017] Creating block rearrangement plan ...
install.sh: line 474: local: warning: overlap_start_sector: circular name reference
install.sh: line 474: warning: overlap_start_sector: circular name reference
install.sh: line 475: local: warning: overlap_end_sector: circular name reference
install.sh: line 475: warning: overlap_end_sector: circular name reference
install.sh: line 480: warning: overlap_start_sector: circular name reference
install.sh: line 481: warning: overlap_end_sector: circular name reference
[... snip ...]
install.sh: line 474: local: warning: overlap_start_sector: circular name reference
install.sh: line 474: warning: overlap_start_sector: circular name reference
install.sh: line 475: local: warning: overlap_end_sector: circular name reference
install.sh: line 475: warning: overlap_end_sector: circular name reference
install.sh: line 480: warning: overlap_start_sector: circular name reference
install.sh: line 481: warning: overlap_end_sector: circular name reference
root@debian-512mb-fra1-01:~# bash --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
```

Then the script seems to bail out to the shell without any other output.

At this point there is a `/d2a/blockplan` file but no `/d2a/mid` dir which is strange enough since it tried to `add_binary_to_mid busybox` so it should be there. Changed some `stage3_prepare` comments into `echo`s.

```
[...]
install.sh: line 475: warning: overlap_end_sector: circular name reference
install.sh: line 480: warning: overlap_start_sector: circular name reference
install.sh: line 481: warning: overlap_end_sector: circular name reference
mount tmpfs
add binaries
root@debian-512mb-fra1-01:~# echo $?
1
root@debian-512mb-fra1-01:~# ls /d2a/mid
ls: cannot access '/d2a/mid': No such file or directory
```

**Comment by lloeki** [comment]
Oh wait, the trap thing unmounts and cleans up the `mid` dir. Obviously.

**Comment by lloeki** [comment]
Busybox being static, `ldd` returns zero lines, hence I suppose `grep` fails or something and the script bails out due to `set -e` + `set -o pipefail`. Wrapped the `ldd` + `while` with a `set +o pipefail` / `set -o pipefail` and it proceeded through to the reboot, but crashed somewhere else. Here's the console output I could capture.

![screen shot 2017-06-21 at 12 33 20](https://user-images.githubusercontent.com/75445/27380065-1255dde8-567e-11e7-9304-ff5a2dda78dc.png)

**Comment by gh2o** [comment]
Thank you for the investigation! I've fixed the script for Debian 9 support.

The reason the console was empty was that in `/proc/cmdline`, `console` was set to `ttyS0` (serial console) so all the important output was discarded and the script hung at a shell when it failed to unmount `/mnt`.

**Comment by lloeki** [comment]
Awesome :) Thanks!
