### ISSUE TITLE
Block storage?

### ISSUE THREAD

**Issue by ajdunevent** [gh2o/digitalocean-debian-to-arch#56]
I tried adding a block storage volume but I couldn't figure out how the volume is represented to Arch.  Does using Arch mean no access to block storage volumes or is there something more that needs to be done (or, more likely, am I just being dense and missing something obvious)?

**Comment by gh2o** [comment]
Do you see them when you run `ls -l /dev/vd*` ?

**Comment by ajdunevent** [comment]
I only have vda1-3. 

It looks like whatever method DO uses to attach the block storage to a droplet doesn't work.  I get an entry under "Volumes" but it isn't attached to any of my droplets.  If I select my Arch droplet, I get a notification that "Sorry! Something went wrong!" and the instructions for how to format and mount the block storage.

**Comment by gh2o** [comment]
I just tried to attach a block volume on SFO2 (on a Debian droplet), and the disk shows up at `/dev/sda`. Running kernel 4.9.82. Does `ls -l /dev/sd*` show anything?

**Comment by ajdunevent** [comment]
Yep, everything seems to work as expected under Arch Linux with kernel 4.15.15 now.  Shows up under /dev/disk/by-id/scsi-* and /dev/sda
