### ISSUE TITLE
Is the locale supposed to be C?

### ISSUE THREAD

**Issue by Olivia5k** [gh2o/digitalocean-debian-to-arch#58]
So, it seems to me the step of running `locale-gen` has been left out of the automatic installation. I assumed all was fine and inevitably ran into encoding errors (`npm` and its super fancy terminal blobbies). Is there any reason to suspect someone would _not_ want `en_US.UTF-8` to be the default locale?

(fantastic project regardless! ❤️ )

**Comment by gh2o** [comment]
Hey! It seems to work fine without it and I didn't want to make too many assumptions about what the user wanted, so I do feel that it can be omitted for now.
