### ISSUE TITLE
Support for floating IPs

### ISSUE THREAD

**Issue by alexshpilkin** [gh2o/digitalocean-debian-to-arch#64]
[Floating IPs][1] should be supported. This basically [boils down][2] to executing

    ip addr add dev eth0 $(curl -sS http://169.254.169.254/metadata/v1/interfaces/public/0/anchor_ipv4/address)

or crafting an equivalent configuration file for networkd. Note that floating IPs are subject to (mild) NAT—they are unshared, but the address obtained above is in 10.0.0.0/8.

[1]: https://blog.digitalocean.com/floating-ips-start-architecting-your-applications-for-high-availability
[2]: https://www.digitalocean.com/community/tutorials/how-to-enable-floating-ips-on-an-older-droplet

**Comment by injust** [comment]
This is already done, see [digitalocean-synchronize.sh#L108-L113](https://github.com/gh2o/digitalocean-debian-to-arch/blob/e6fa59d82116935ae038627d2ef7940ccdbb6b9a/aur/digitalocean-synchronize.sh#L108-L113).

**Comment by marco-m** [comment]
@gh2o it looks like this can be closed as done ?
