### ISSUE TITLE
sshd not active after reboot

### ISSUE THREAD

**Issue by kim366** [gh2o/digitalocean-debian-to-arch#69]
When I reboot my droplet, I get connection refused on port 22 when trying to connect with ssh. Only after I log in through the DigitalOcean console, does (presumably) sshd start and I can connect via ssh. Why does sshd not start before the login on the physical machine? Or should I make a dummy user with no password that automatically logs in to start this service?

**Comment by z3ntu** [comment]
`systemctl enable sshd.service` ?

**Comment by kim366** [comment]
`systemctl enable sshd.socket` was the solution. Thanks!
