### ISSUE TITLE
Sanity checks fail with debian 9.11

### ISSUE THREAD

**Issue by ghost** [gh2o/digitalocean-debian-to-arch#76]
I've been running a few droplets for a while using this excellent script. Today I needed a s-2vcpu-4gb droplet for custom kernel building and I ran into issues. The sanity_checks() function in [install.sh](https://github.com/gh2o/digitalocean-debian-to-arch/blob/debian9/install.sh#L261) always failed with /etc/debian_version being 9.11. Seems like it can't handle the double minor version digits. My non-existing regex-fu, together with being a bit pressed for time made me decide to uncomment the relevant test lines. I'm sure there's a more elegant/less crude fix to support debian 9.11 on DO.

Thanks for keeping this alive!

**Comment by xqdzn** [comment]
@glitsj16 just double the question mark. [ "$(cat /etc/debian_version)" == [89].?? ]]
