### ISSUE TITLE
unable to boot

### ISSUE THREAD

**Issue by cigarplug** [gh2o/digitalocean-debian-to-arch#80]
Hi
Thanks for the script. I'm having trouble booting after running it. The error I get is:

> ERROR: Root device mounted successfully, but /sbin/init does not exist. 
Bailing out, you are on your own now. Good luck.

I found a similar issue [here](https://unix.stackexchange.com/questions/96720/sbin-init-does-not-exist-bailing-out-you-are-on-your-own-good-luck), but there's no prompt in your script for `resolvconf` user input

**Comment by z3ntu** [comment]
#79 should fix that. The `systemd-sysvcompat` package was removed from the base group but it is a dependency of the base metapackage.

**Comment by z3ntu** [comment]
@cigarplug #79 was merged now - could you please try again now?

**Comment by cigarplug** [comment]
@z3ntu Thanks for the fix. I spawned a new droplet and it worked. Cheers
